# NUMPY

In [1]:
###convention for importing numpy 

import numpy as np

In [2]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)  ##prints the length and width

(4,)


In [5]:
print(a.dtype)

int32


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
np.random.random([2, 3])

array([[0.03895097, 0.41568687, 0.12056095],
       [0.1799961 , 0.31104505, 0.5702614 ]])

In [8]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [14]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [15]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [16]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [17]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [18]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

# PANDAS

In [24]:
import pandas as pd

In [25]:
days = pd.Series(["Monday", "Tuesday", "Wednesday"])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [26]:
days[0]

'Monday'

In [27]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [29]:
df_dict = {"Country": ["Ghana", "Kenya", "Nigeria",
                      "Togo"],
          "Capital": ["Accra", "Nairobi",
                     "Abuja", "Lome"],
          "Population": [10089, 8580,
                        35000, 120000],
          "Age": [60, 70, 80, 75]}
df = pd.DataFrame(df_dict, index =[2, 4, 6, 8])

In [30]:
df

Country  Capital  Population  Age
2    Ghana    Accra       10089   60
4    Kenya  Nairobi        8580   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome      120000   75

In [31]:
df_list = [["Ghana", "Accra", 10089,  60],
          ["Kenya", "Nairobi", 8580, 70],
          ["Nigeria", "Abuja", 35000, 80],
          ["Togo", "Lome", 120000, 75]]
df1 = pd.DataFrame(df_list, columns = ["Country",
                                      "Capital",
                                      "Population",
                                      "Age"])

In [32]:
df1

Country  Capital  Population  Age
0    Ghana    Accra       10089   60
1    Kenya  Nairobi        8580   70
2  Nigeria    Abuja       35000   80
3     Togo     Lome      120000   75

In [33]:
df.describe()

Population        Age
count       4.00000   4.000000
mean    43417.25000  71.250000
std     52472.76732   8.539126
min      8580.00000  60.000000
25%      9711.75000  67.500000
50%     22544.50000  72.500000
75%     56250.00000  76.250000
max    120000.00000  80.000000